ingress:
  enabled: true
  hosts:
    - grafana.home.lab
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  ingressClassName: nginx
  tls:
  - secretName: grafana-tls-secret
    hosts:
      - grafana.home.lab
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      url: http://vmsingle-single.vm.svc:8429
      access: proxy
      isDefault: true
dashboards:
  default:
    apiserver:
      url: https://raw.githubusercontent.com/cemehov/argocd-demo/main/observability/grafana/dashboards/apiserver.json
    cluster-total:
      url: https://raw.githubusercontent.com/cemehov/argocd-demo/main/observability/grafana/dashboards/cluster-total.json
